import { OrganizationRole, ROLES } from "./roles.js";

export const PERMISSIONS = {
  // Organization
  ORGANIZATION_READ: "ORGANIZATION_READ",
  ORGANIZATION_UPDATE: "ORGANIZATION_UPDATE",
  ORGANIZATION_DELETE: "ORGANIZATION_DELETE",

  // Members
  MEMBER_READ: "MEMBER_READ",
  MEMBER_INVITE: "MEMBER_INVITE",
  MEMBER_UPDATE_ROLE: "MEMBER_UPDATE_ROLE",
  MEMBER_REMOVE: "MEMBER_REMOVE",

  // Projects
  PROJECT_CREATE: "PROJECT_CREATE",
  PROJECT_READ: "PROJECT_READ",
  PROJECT_UPDATE: "PROJECT_UPDATE",
  PROJECT_DELETE: "PROJECT_DELETE",

  // Tasks
  TASK_CREATE: "TASK_CREATE",
  TASK_READ: "TASK_READ",
  TASK_UPDATE: "TASK_UPDATE",
  TASK_ASSIGN: "TASK_ASSIGN",
  TASK_DELETE: "TASK_DELETE",

  // Comments
  COMMENT_CREATE: "COMMENT_CREATE",
  COMMENT_READ: "COMMENT_READ",
  COMMENT_DELETE: "COMMENT_DELETE",

  // Attachments
  ATTACHMENT_UPLOAD: "ATTACHMENT_UPLOAD",
  ATTACHMENT_READ: "ATTACHMENT_READ",
  ATTACHMENT_DELETE: "ATTACHMENT_DELETE",

  // Analytics & Activity
  ANALYTICS_READ: "ANALYTICS_READ",
  ACTIVITY_READ: "ACTIVITY_READ",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<OrganizationRole, Permission[]> = {
  [ROLES.OWNER]: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.ORGANIZATION_UPDATE,
    PERMISSIONS.ORGANIZATION_DELETE,
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.MEMBER_INVITE,
    PERMISSIONS.MEMBER_UPDATE_ROLE,
    PERMISSIONS.MEMBER_REMOVE,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_DELETE,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_DELETE,
    PERMISSIONS.COMMENT_CREATE,
    PERMISSIONS.COMMENT_READ,
    PERMISSIONS.COMMENT_DELETE,
    PERMISSIONS.ATTACHMENT_UPLOAD,
    PERMISSIONS.ATTACHMENT_READ,
    PERMISSIONS.ATTACHMENT_DELETE,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.ACTIVITY_READ,
  ],

  [ROLES.ADMIN]: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.ORGANIZATION_UPDATE,
    // Note: ORGANIZATION_DELETE is excluded for ADMIN (only OWNER can delete organization)
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.MEMBER_INVITE,
    PERMISSIONS.MEMBER_UPDATE_ROLE,
    PERMISSIONS.MEMBER_REMOVE,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_DELETE,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_DELETE,
    PERMISSIONS.COMMENT_CREATE,
    PERMISSIONS.COMMENT_READ,
    PERMISSIONS.COMMENT_DELETE,
    PERMISSIONS.ATTACHMENT_UPLOAD,
    PERMISSIONS.ATTACHMENT_READ,
    PERMISSIONS.ATTACHMENT_DELETE,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.ACTIVITY_READ,
  ],

  [ROLES.MANAGER]: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_DELETE,
    PERMISSIONS.COMMENT_CREATE,
    PERMISSIONS.COMMENT_READ,
    PERMISSIONS.COMMENT_DELETE,
    PERMISSIONS.ATTACHMENT_UPLOAD,
    PERMISSIONS.ATTACHMENT_READ,
    PERMISSIONS.ATTACHMENT_DELETE,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.ACTIVITY_READ,
  ],

  [ROLES.MEMBER]: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.COMMENT_CREATE,
    PERMISSIONS.COMMENT_READ,
    PERMISSIONS.ATTACHMENT_UPLOAD,
    PERMISSIONS.ATTACHMENT_READ,
    PERMISSIONS.ACTIVITY_READ,
  ],
};
